### ISSUE TITLE
Demo does not make important/relevant benchmarking information clear

### ISSUE THREAD

**Issue by dbkaplun** [web-perf/react-worker-dom#3]
http://web-perf.github.io/react-worker-dom/ just looks like a bunch of rows with flickering numbers and doesn't seem to have any useful information. Would be great if I could see just a simple benchmark:

* How long does it take to render 1000 rows with workers?
* How long does it take to render 1000 rows without workers?

FWIW I've found JSperf very useful for things like this.

**Comment by axemclion** [comment]
Note that JSPerf is not the right tool for benchmarking here since it only measures the time taken by Javascript to run. Regardless of Javascript running in a worker or the main UI thread, the time it takes is usually the same.

For specific benchmarking in this case, one would be interested in the browser rendering time. Something like [browser-perf](https://github.com/axemclion/browser-perf/) or simply opening the Chromedevtools and starting the Frame Rate panel. 

Unfortunately, there is no simply way to show the frame rate panel. We could use some of the FPS meters, but they rely on requestAnimationFrame which is much less accurate than the information that the Chrome dev tools provides. This information is only available in the chrome tracing which is not accessible to the web page. 

Maybe we could put this information on the home page I guess. I have also written a blog with more specific numbers [here](http://blog.nparashuram.com/2015/12/react-web-worker-renderer.html)

**Comment by axemclion** [comment]
Closing this issue. Please reopen if you think the explanation is not satisfactory
