### ISSUE TITLE
ToDo WebWorker demo bug

### ISSUE THREAD

**Issue by montogeek** [web-perf/react-worker-dom#6]
Hi!

Great examples :)

I noticed something, the TODO app with WebWorkers does not clear the input value after adding it, while the version without WebWorkers does it.

**Comment by axemclion** [comment]
@montogeek This is an issue because I have not implemented the AutoFocus util that react-dom implements. React-Dom has a special wrapper for input box ([like this](https://github.com/facebook/react/blob/bbd5a78efaf92b7ffcde2a1923112b8931855209/src/renderers/dom/client/wrappers/ReactDOMInput.js)), while I do not handle that case yet. 

That is in next in the todo list.
